### ISSUE TITLE
Definition of 'Counts'?

### ISSUE THREAD

**Issue by pfuerholz** [abhiaiyer91/How-We-Redux-Todos#3]
Thanks for really cool introduction into Meteor with Redux on https://www.medium.com! I went through it and downloaded your code from this Github-repo. Unfortunately I get a 'ReferenceError: Counts is not defined' error in the browser. As I've seen 'Counts' is used in publications.json and in TodoList.jsx but I could nowhere find a place where it is defined.

**Comment by abhiaiyer91** [comment]
Hey there!
you will need to install the Publish Counts package from Atmosphere. or `meteor add tmesday:publish-counts`

**Comment by pfuerholz** [comment]
Thanks for pointing out this! (Pls notice small typo: `tmeasday:publish-counts`)
(As I have seen in your GIT repo I had to add following meteor packages as well:
`reactive-dict`, `reactive-var` and `twbs:bootstrap`)
**Your tutorial was exactly was I was looking for! Thanks a lot!**
