### ISSUE TITLE
showVisibilityFilter for multipleLists

### ISSUE THREAD

**Issue by Falieson** [abhiaiyer91/How-We-Redux-Todos#9]
sorry I'm still a reduxing newb, thanks so much for your work and tutorials on this. My goal is to continue your teaching with my planetx-boilerplate repo.

[![planetx_branch-5-B_taskList-toggle-showCompleted.png](https://files.gitter.im/meteor/meteor/NF6E/thumb/planetx_branch-5-B_taskList-toggle-showCompleted.png)](https://files.gitter.im/meteor/meteor/NF6E/planetx_branch-5-B_taskList-toggle-showCompleted.png)
I’m looking for some guidance on how to approach this,  I have a task list toggler “show completed tasks”, but instead of 1 list like in your tutorial I have multiple lists. How do I change the setVisibilityFilter to only apply to a single list? When I hit the toggler now, all the togglers change and all completed tasks are hidden. [[My Code](
https://github.com/Falieson/planetx-boilerplate/blob/5/extraCredit/task_expiration/imports/ui/components/taskList/CompletedToggler.jsx#L6)]

I've also asked this over in [the forums](https://forums.meteor.com/t/react-beyond-how-we-redux-how-to-visfilter-for-multiple-lists-sneak-peak-at-planetx-boilerplate/24938)

**Comment by abhiaiyer91** [comment]
Sure @Falieson you could something like this...

change you `visibilityReducer` to a `higher order reducer`

```js
compostVisibilityReducer(listName) {
  return function visibilityFilter(state = 'SHOW_ALL', action = {}) {
    switch (action.type) {
      case `SET_VISIBILITY_FILTER_${listName}`:
        return action.filter;
      default:
        return state;
    }
  }
}
```

now you can apply these as separate reducers here:

```js
const rootReducer = combineReducers({
  visibilityFilterListOne: composeVisibilityFilter('list1'),
  visibilityFilterListTwo: composeVisibilityFilter('list2'),
  visibilityFilterListThree: composeVisibilityFilter('list3'),
});
```

This separates out the state in separate reducers to manage visbility of the list

**Comment by abhiaiyer91** [comment]
There are other ways to do this too, in one reducer as well. but idk, not into that solution
